# Generated by Django 5.2.12 on 2026-04-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_scholar_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
