# Generated by Django 5.2.12 on 2026-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roadmap_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Roadmap'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='scopus_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Scopus'),
        ),
    ]
