# Generated by Django 5.2.12 on 2026-03-18 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('PENELITIAN', 'Penelitian'), ('PENGABDIAN', 'Pengabdian Masyarakat')], max_length=20)),
                ('nominal_biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deskripsi', models.TextField()),
                ('tahun_akademik', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Proposal'), ('ONGOING', 'Ongoing / Pelaksanaan'), ('WAITING_KAPRODI_REVIEW', 'Menunggu Review Kaprodi'), ('REVISION_KAPRODI', 'Revisi dari Kaprodi'), ('WAITING_DEKAN_REVIEW', 'Menunggu Review Dekan'), ('REVISION_DEKAN', 'Revisi dari Dekan'), ('APPROVED_FINAL', 'Selesai / Approved Final')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('PROPOSAL', 'Proposal Diterima'), ('LAPORAN_AKHIR', 'Laporan Akhir'), ('LUARAN', 'Bukti Luaran')], max_length=20)),
                ('file', models.FileField(upload_to='dokumen_kegiatan/')),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='kegiatan.kegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_logs', to='kegiatan.kegiatan')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kegiatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.kegiatan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('KAPRODI', 'Tingkat Kaprodi'), ('DEKAN', 'Tingkat Dekan')], max_length=20)),
                ('keputusan', models.CharField(choices=[('APPROVE', 'Approve'), ('REVISE', 'Revise'), ('REJECT', 'Reject')], max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aktor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='kegiatan.kegiatan')),
            ],
        ),
    ]
