# Generated by Django 5.2.12 on 2026-04-11 14:05

import kegiatan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='integrasi_mata_kuliah',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='kategori_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='link_jurnal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='status_pelaksanaan',
            field=models.CharField(choices=[('ONGOING', 'On going'), ('PUBLISHED', 'Sudah publish')], default='ONGOING', max_length=20),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(upload_to='dokumen_kegiatan/', validators=[kegiatan.models.validate_pdf_extension, kegiatan.models.validate_file_size]),
        ),
    ]
