# Generated by Django 5.2.12 on 2026-04-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_kegiatan_integrasi_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='nominal_biaya',
        ),
    ]
