# Generated by Django 5.2.12 on 2026-04-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0003_remove_kegiatan_nominal_biaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='keputusan',
            field=models.CharField(choices=[('APPROVE', 'Sesuai'), ('REVISE', 'Tidak Sesuai')], max_length=20),
        ),
    ]
