# Generated by Django 5.2.12 on 2026-04-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0004_alter_reviewlog_keputusan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Mata Kuliah',
                'verbose_name_plural': 'Daftar Mata Kuliah',
                'ordering': ['nama'],
            },
        ),
        # Clear old text values so they don't violate the FK constraint
        migrations.RunSQL(
            "UPDATE kegiatan_kegiatan SET integrasi_mata_kuliah = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='integrasi_mata_kuliah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kegiatan.matakuliah', verbose_name='Integrasi Mata Kuliah'),
        ),
    ]
