# Generated by Django 5.2.12 on 2026-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0005_matakuliah_alter_kegiatan_integrasi_mata_kuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='semester',
            field=models.CharField(choices=[('GANJIL', 'Semester Ganjil'), ('GENAP', 'Semester Genap')], default='GANJIL', max_length=10),
        ),
    ]
