# Generated by Django 5.2.12 on 2026-06-09 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0006_kegiatan_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='tim_dosen',
            field=models.ManyToManyField(related_name='tim_kegiatan', to=settings.AUTH_USER_MODEL, verbose_name='Tim Dosen'),
        ),
    ]
