# Generated by Django 5.2.12 on 2026-06-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0007_kegiatan_tim_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='sumber_pendanaan',
            field=models.CharField(choices=[('MANDIRI', 'Mandiri'), ('HIBAH', 'Hibah')], default='MANDIRI', max_length=20, verbose_name='Sumber Pendanaan'),
        ),
    ]
