# Generated by Django 5.2.12 on 2026-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0008_kegiatan_sumber_pendanaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kegiatan',
            name='integrasi_mata_kuliah',
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='integrasi_mata_kuliah',
            field=models.ManyToManyField(blank=True, to='kegiatan.matakuliah', verbose_name='Integrasi Mata Kuliah'),
        ),
    ]
