# Generated by Django 5.2.12 on 2026-06-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0009_remove_kegiatan_integrasi_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='keputusan',
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='keputusan_integrasi_mk',
            field=models.CharField(choices=[('APPROVE', 'Sesuai'), ('REVISE', 'Tidak Sesuai')], default='APPROVE', max_length=20, verbose_name='Keputusan Integrasi Mata Kuliah'),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='keputusan_roadmap',
            field=models.CharField(choices=[('APPROVE', 'Sesuai'), ('REVISE', 'Tidak Sesuai')], default='APPROVE', max_length=20, verbose_name='Keputusan Roadmap'),
        ),
    ]
