# Generated by Django 5.2.12 on 2026-06-10 14:34

import kegiatan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0010_remove_reviewlog_keputusan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='dokumen_kegiatan/', validators=[kegiatan.models.validate_pdf_extension, kegiatan.models.validate_file_size]),
        ),
    ]
